#snmp_hass_config
#edit configuration.yaml or add file !include
sensor:
    - platform: snmp
      name: "comet_temperatura"
      host: 192.168.1.213 #change IP address
      baseoid: 1.3.6.1.4.1.22626.1.2.1.1.0
      unit_of_measurement: "°C"
      accept_errors: true
      device_class: temperature
      state_class: measurement
      
    - platform: snmp
      name: "comet_wilgotnosc"
      host: 192.168.1.213 #change IP address
      baseoid: 1.3.6.1.4.1.22626.1.2.1.2.0
      unit_of_measurement: "%"
      accept_errors: true
      device_class: humidity
      state_class: measurement
